-- PostgreSQL 12+ schema and demo data for Smart Vehicle Service Management System.
-- In pgAdmin, first create a database named smart_vehicle_service, connect to it,
-- then open this file in Query Tool and execute the whole script.

CREATE TABLE IF NOT EXISTS customers (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vehicles (
    vehicle_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    vehicle_number VARCHAR(20) NOT NULL UNIQUE,
    vehicle_type VARCHAR(40) NOT NULL,
    brand VARCHAR(60) NOT NULL,
    model VARCHAR(60) NOT NULL,
    manufacturing_year SMALLINT NOT NULL,
    CONSTRAINT uq_vehicle_customer UNIQUE (vehicle_id, customer_id),
    CONSTRAINT fk_vehicles_customer FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id) ON DELETE CASCADE,
    CONSTRAINT chk_vehicle_year CHECK (manufacturing_year BETWEEN 1886 AND 2100)
);

CREATE TABLE IF NOT EXISTS mechanics (
    mechanic_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mechanic_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL UNIQUE,
    specialization VARCHAR(100) NOT NULL,
    availability VARCHAR(20) NOT NULL DEFAULT 'available',
    CONSTRAINT chk_mechanic_availability
        CHECK (availability IN ('available', 'busy', 'unavailable'))
);

CREATE TABLE IF NOT EXISTS services (
    service_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500) NOT NULL,
    service_cost NUMERIC(10, 2) NOT NULL,
    CONSTRAINT chk_service_cost CHECK (service_cost >= 0)
);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    vehicle_id INTEGER NOT NULL,
    service_id INTEGER NOT NULL,
    mechanic_id INTEGER,
    booking_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    service_date DATE NOT NULL,
    problem_description VARCHAR(1000) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    CONSTRAINT uq_booking_customer UNIQUE (booking_id, customer_id),
    CONSTRAINT fk_bookings_customer FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id) ON DELETE CASCADE,
    CONSTRAINT fk_bookings_vehicle_customer FOREIGN KEY (vehicle_id, customer_id)
        REFERENCES vehicles(vehicle_id, customer_id) ON DELETE CASCADE,
    CONSTRAINT fk_bookings_service FOREIGN KEY (service_id)
        REFERENCES services(service_id) ON DELETE RESTRICT,
    CONSTRAINT fk_bookings_mechanic FOREIGN KEY (mechanic_id)
        REFERENCES mechanics(mechanic_id) ON DELETE SET NULL,
    CONSTRAINT chk_booking_status
        CHECK (status IN ('pending', 'confirmed', 'in_progress', 'completed', 'cancelled')),
    CONSTRAINT chk_service_date CHECK (service_date >= DATE '2000-01-01')
);

CREATE TABLE IF NOT EXISTS spare_parts (
    part_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_name VARCHAR(120) NOT NULL UNIQUE,
    quantity INTEGER NOT NULL DEFAULT 0,
    price NUMERIC(10, 2) NOT NULL,
    supplier VARCHAR(120) NOT NULL,
    CONSTRAINT chk_part_quantity CHECK (quantity >= 0),
    CONSTRAINT chk_part_price CHECK (price >= 0)
);

CREATE TABLE IF NOT EXISTS booking_parts (
    booking_id INTEGER NOT NULL,
    part_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    PRIMARY KEY (booking_id, part_id),
    CONSTRAINT fk_booking_parts_booking FOREIGN KEY (booking_id)
        REFERENCES bookings(booking_id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_parts_part FOREIGN KEY (part_id)
        REFERENCES spare_parts(part_id) ON DELETE RESTRICT,
    CONSTRAINT chk_booking_part_quantity CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS payments (
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    payment_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    payment_method VARCHAR(20) NOT NULL,
    payment_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id)
        REFERENCES bookings(booking_id) ON DELETE CASCADE,
    CONSTRAINT fk_payments_booking_customer FOREIGN KEY (booking_id, customer_id)
        REFERENCES bookings(booking_id, customer_id) ON DELETE CASCADE,
    CONSTRAINT fk_payments_customer FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id) ON DELETE CASCADE,
    CONSTRAINT chk_payment_amount CHECK (amount > 0),
    CONSTRAINT chk_payment_method
        CHECK (payment_method IN ('cash', 'card', 'upi', 'bank_transfer')),
    CONSTRAINT chk_payment_status
        CHECK (payment_status IN ('pending', 'paid', 'refunded'))
);

CREATE TABLE IF NOT EXISTS service_history (
    history_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INTEGER NOT NULL UNIQUE,
    service_date DATE NOT NULL,
    cost NUMERIC(10, 2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'completed',
    CONSTRAINT fk_history_booking FOREIGN KEY (booking_id)
        REFERENCES bookings(booking_id) ON DELETE CASCADE,
    CONSTRAINT chk_history_cost CHECK (cost >= 0),
    CONSTRAINT chk_history_status CHECK (status IN ('completed', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS admin (
    admin_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(60) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);

-- Demo credentials: admin / admin123; customer account: demo@example.com / Customer123!
INSERT INTO admin (username, password_hash)
VALUES ('admin', 'pbkdf2:sha256:600000$svs-admin-seed$5d07c32721b651d26ce4d7bce85322af1aa79c3051e8248275facea211e57b63')
ON CONFLICT (username) DO NOTHING;

INSERT INTO customers (full_name, email, phone, password_hash)
VALUES ('Demo Customer', 'demo@example.com', '+1-555-0101',
 'pbkdf2:sha256:600000$svs-customer-seed$ab88766b760633da60d8da677abbe1ed91013c684f408cf7c1cfaebb09966a14')
ON CONFLICT (email) DO NOTHING;

INSERT INTO mechanics (mechanic_name, phone, specialization, availability)
VALUES
 ('Aarav Sharma', '+1-555-0201', 'Engine diagnostics', 'available'),
 ('Mia Patel', '+1-555-0202', 'Brakes and suspension', 'available')
ON CONFLICT (phone) DO NOTHING;

INSERT INTO services (service_name, description, service_cost)
VALUES
 ('General Service', 'Oil, filter, fluid and safety inspection.', 89.00),
 ('Brake Inspection', 'Brake pad, disc and fluid inspection.', 55.00),
 ('Engine Diagnostics', 'Computerized engine fault diagnosis.', 75.00)
ON CONFLICT (service_name) DO NOTHING;

INSERT INTO spare_parts (part_name, quantity, price, supplier)
VALUES
 ('Engine Oil Filter', 30, 12.50, 'AutoSupply Co.'),
 ('Brake Pad Set', 18, 48.00, 'RoadReady Parts')
ON CONFLICT (part_name) DO NOTHING;

INSERT INTO vehicles (customer_id, vehicle_number, vehicle_type, brand, model, manufacturing_year)
SELECT customer_id, 'DEMO-100', 'Car', 'Toyota', 'Corolla', 2021
FROM customers WHERE email = 'demo@example.com'
ON CONFLICT (vehicle_number) DO NOTHING;

INSERT INTO bookings (customer_id, vehicle_id, service_id, mechanic_id, service_date, problem_description)
SELECT c.customer_id, v.vehicle_id, s.service_id, m.mechanic_id,
       CURRENT_DATE + 7, 'Demo booking for testing the service workflow.'
FROM customers c
JOIN vehicles v ON v.customer_id = c.customer_id AND v.vehicle_number = 'DEMO-100'
JOIN services s ON s.service_name = 'General Service'
LEFT JOIN mechanics m ON m.mechanic_name = 'Aarav Sharma'
WHERE c.email = 'demo@example.com'
  AND NOT EXISTS (
      SELECT 1 FROM bookings b
      WHERE b.customer_id = c.customer_id AND b.vehicle_id = v.vehicle_id
        AND b.service_id = s.service_id
        AND b.problem_description = 'Demo booking for testing the service workflow.'
  );

INSERT INTO payments (booking_id, customer_id, amount, payment_method, payment_status)
SELECT b.booking_id, b.customer_id, s.service_cost, 'cash', 'paid'
FROM bookings b
JOIN services s ON s.service_id = b.service_id
JOIN customers c ON c.customer_id = b.customer_id
WHERE c.email = 'demo@example.com'
  AND b.problem_description = 'Demo booking for testing the service workflow.'
  AND NOT EXISTS (SELECT 1 FROM payments p WHERE p.booking_id = b.booking_id);

DROP TRIGGER IF EXISTS trg_booking_parts_before_insert ON booking_parts;
DROP TRIGGER IF EXISTS trg_booking_parts_after_delete ON booking_parts;
DROP TRIGGER IF EXISTS trg_booking_history_after_update ON bookings;
DROP FUNCTION IF EXISTS fn_booking_parts_before_insert();
DROP FUNCTION IF EXISTS fn_booking_parts_after_delete();
DROP FUNCTION IF EXISTS fn_booking_history_after_update();
DROP PROCEDURE IF EXISTS sp_customer_booking_summary(INTEGER, BIGINT, BIGINT);
DROP FUNCTION IF EXISTS fn_booking_total(INTEGER);
DROP VIEW IF EXISTS v_service_history;

CREATE FUNCTION fn_booking_parts_before_insert()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    available_quantity INTEGER;
BEGIN
    SELECT quantity INTO available_quantity
    FROM spare_parts
    WHERE part_id = NEW.part_id
    FOR UPDATE;

    IF available_quantity IS NULL OR available_quantity < NEW.quantity THEN
        RAISE EXCEPTION 'Insufficient spare-part stock';
    END IF;

    UPDATE spare_parts
    SET quantity = quantity - NEW.quantity
    WHERE part_id = NEW.part_id;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_booking_parts_before_insert
BEFORE INSERT ON booking_parts
FOR EACH ROW EXECUTE FUNCTION fn_booking_parts_before_insert();

CREATE FUNCTION fn_booking_parts_after_delete()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE spare_parts
    SET quantity = quantity + OLD.quantity
    WHERE part_id = OLD.part_id;
    RETURN OLD;
END;
$$;

CREATE TRIGGER trg_booking_parts_after_delete
AFTER DELETE ON booking_parts
FOR EACH ROW EXECUTE FUNCTION fn_booking_parts_after_delete();

CREATE FUNCTION fn_booking_history_after_update()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.status IN ('completed', 'cancelled')
       AND NEW.status IS DISTINCT FROM OLD.status THEN
        INSERT INTO service_history (booking_id, service_date, cost, status)
        SELECT NEW.booking_id, NEW.service_date, s.service_cost, NEW.status
        FROM services s
        WHERE s.service_id = NEW.service_id
        ON CONFLICT (booking_id) DO UPDATE
        SET service_date = EXCLUDED.service_date,
            cost = EXCLUDED.cost,
            status = EXCLUDED.status;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_booking_history_after_update
AFTER UPDATE ON bookings
FOR EACH ROW EXECUTE FUNCTION fn_booking_history_after_update();

CREATE FUNCTION fn_booking_total(p_booking_id INTEGER)
RETURNS NUMERIC(10, 2)
LANGUAGE SQL
STABLE
AS $$
    SELECT COALESCE((
        SELECT s.service_cost
        FROM bookings b
        JOIN services s ON s.service_id = b.service_id
        WHERE b.booking_id = p_booking_id
    ), 0) + COALESCE((
        SELECT SUM(bp.quantity * sp.price)
        FROM booking_parts bp
        JOIN spare_parts sp ON sp.part_id = bp.part_id
        WHERE bp.booking_id = p_booking_id
    ), 0)::NUMERIC(10, 2);
$$;

CREATE PROCEDURE sp_customer_booking_summary(
    IN p_customer_id INTEGER,
    INOUT p_booking_count BIGINT,
    INOUT p_completed_count BIGINT
)
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT COUNT(b.booking_id),
           COUNT(b.booking_id) FILTER (WHERE b.status = 'completed')
    INTO p_booking_count, p_completed_count
    FROM customers c
    LEFT JOIN bookings b ON b.customer_id = c.customer_id
    WHERE c.customer_id = p_customer_id
    GROUP BY c.customer_id;

    IF NOT FOUND THEN
        p_booking_count := 0;
        p_completed_count := 0;
    END IF;
END;
$$;

CREATE VIEW v_service_history AS
SELECT h.history_id, b.booking_id, c.customer_id, c.full_name,
       v.vehicle_number, s.service_name AS service_performed,
       h.service_date, m.mechanic_name, h.cost, h.status
FROM service_history h
JOIN bookings b ON b.booking_id = h.booking_id
JOIN customers c ON c.customer_id = b.customer_id
JOIN vehicles v ON v.vehicle_id = b.vehicle_id
JOIN services s ON s.service_id = b.service_id
LEFT JOIN mechanics m ON m.mechanic_id = b.mechanic_id;
